apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    description: ""
  creationTimestamp: "2021-04-24T21:55:59Z"
  generation: 2
  labels:
    appgroup: ""
  name: kuber-site
  namespace: default
  resourceVersion: "24611544"
  selfLink: /apis/apps/v1/namespaces/default/deployments/kuber-site
  uid: 9f04687f-1c98-416b-b8dc-f42766b93c6a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kuber-site
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"","path":"","port":"","names":""}]'
      creationTimestamp: null
      labels:
        app: kuber-site
    spec:
      affinity: {}
      containers:
      - env:
        - name: PAAS_APP_NAME
          value: kuber-site
        - name: PAAS_NAMESPACE
          value: default
        - name: PAAS_PROJECT_ID
          value: 0aa90c82b500259c2fddc0012a6ddfd6
        image: ghostklart/kuber-site:latest
        imagePullPolicy: Always
        name: container-0
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx
          name: cce-obs-import-nginx
      dnsConfig:
        options:
        - name: timeout
          value: ""
        - name: ndots
          value: "5"
        - name: single-request-reopen
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
      volumes:
      - name: cce-obs-import-nginx
        persistentVolumeClaim:
          claimName: cce-obs-import-nginx
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-04-24T21:56:40Z"
    lastUpdateTime: "2021-04-24T21:56:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-04-24T21:55:59Z"
    lastUpdateTime: "2021-04-24T21:56:40Z"
    message: ReplicaSet "kuber-site-77555c574b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
